---
# tasks file for webserver
- name: Configure webserver
  package:
          name: "httpd"
          state: present
- name: Copy file
  get_url: 
           url: "https://raw.githubusercontent.com/Rajnish-TheGreat/Website/main/index.html" 
           dest: "/var/www/html"

- name: Start the service
  service:
          name: "httpd"
          state: started
  notify: Start the service 
